MMS.Web/Controllers/StockTransferMasterController.cs
using MMS.Common;
using MMS.Core.Entities;
using MMS.Repository.Managers;
using MMS.Web.Models.StockTransferModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MMS.Web.Controllers
{
    [CustomFilter]
    public class StockTransferMasterController : Controller
    {
        #region Accounts View

        [HttpGet]
        public ActionResult StockTransferMaster()
        {
            StockTransferModel vm = new StockTransferModel();
            return View(vm);
        }
        public ActionResult StockTransferMasterGrid()
        {
            StockTransferModel vm = new StockTransferModel();
            StockTransferManager stockManager = new StockTransferManager();
            vm.StockTransferMasterList = stockManager.Get();
            return PartialView("Partial/StockTransferMasterGrid", vm);
        }
        [HttpPost]
        public ActionResult StockTransferMasterDetails(int StockTransferID)
        {
            StockTransferManager stockManager = new StockTransferManager();
            StockTransferMaster stockMaster = new  StockTransferMaster();
            StockTransferModel model = new StockTransferModel();
            stockMaster = stockManager.GetStockTransferMasterId(StockTransferID);
            if (stockMaster != null)
            {
                model.StockTransferID =stockMaster.StockTransferID;
                model.GrnTypeMasterId =stockMaster.GrnTypeMasterId;
                model.GRNNo =stockMaster.GRNNo;
                model.IssuedTo =stockMaster.IssuedTo;
                model.StoreMasterId =stockMaster.StoreMasterId;
                model.TransportDetails =stockMaster.TransportDetails;
                model.Remarks =stockMaster.Remarks;
                model.Rate =stockMaster.Rate;
                model.Value =stockMaster.Value;
                model.PartyDCNo = stockMaster.PartyDCNo;
                model.MatCategoryId =stockMaster.MatCategoryId;
                model.MatGroupId =stockMaster.MatGroupId;
                model.ColourId =stockMaster.ColourId;
                model.Quantity =stockMaster.Quantity;
                model.ClosingStockInAllStores =stockMaster.ClosingStockInAllStores;
                model.ClosingStockingInCurrentStores =stockMaster.ClosingStockingInCurrentStores;
                model.ReservedStock =stockMaster.ReservedStock;
                model.FreeStock =stockMaster.FreeStock;
                model.InvoiceRef = Convert.ToDateTime(stockMaster.InvoiceRef ).Date.ToString("dd/MM/yyyy");
                model.InvoiceDate = Convert.ToDateTime(stockMaster.InvoiceDate).Date.ToString("dd/MM/yyyy"); 
                model.CreatedBy = stockMaster.CreatedBy;
                model.UpdatedBy = stockMaster.UpdatedBy;
                model.CreatedDate = stockMaster.CreatedDate;
                model.UpdatedDate = stockMaster.UpdatedDate;

              
            }
            return PartialView("Partial/StockTransferMasterDetails", model);
        }
        #endregion

        #region Curd Operation
        [HttpPost]
        public ActionResult  StockTransferMaster(StockTransferModel model)
        {
             StockTransferMaster StockTransferMasters = new  StockTransferMaster();
             StockTransferMaster StockTransferMaster = new StockTransferMaster();
            if (ModelState.IsValid)
            {
                StockTransferManager stockManager = new StockTransferManager();
                StockTransferMaster = stockManager.GetGRNNo(model.GRNNo);
                if (StockTransferMaster == null)
                {
                    StockTransferMasters.StockTransferID =  model.StockTransferID;
                    StockTransferMasters.GrnTypeMasterId =  model.GrnTypeMasterId;
                    StockTransferMasters.GRNNo =  model.GRNNo;
                    StockTransferMasters.IssuedTo =  model.IssuedTo;
                    StockTransferMasters.StoreMasterId =  model.StoreMasterId;
                    StockTransferMasters.TransportDetails =  model.TransportDetails;
                    StockTransferMasters.Remarks =  model.Remarks;
                    StockTransferMasters.Rate =  model.Rate;
                    StockTransferMasters.Value =  model.Value;
                    StockTransferMasters.PartyDCNo = model.PartyDCNo;
                    StockTransferMasters.MatCategoryId =  model.MatCategoryId;
                    StockTransferMasters.MatGroupId =  model.MatGroupId;
                    StockTransferMasters.ColourId =  model.ColourId;
                    StockTransferMasters.Quantity =  model.Quantity;
                    StockTransferMasters.ClosingStockInAllStores =  model.ClosingStockInAllStores;
                    StockTransferMasters.ClosingStockingInCurrentStores =  model.ClosingStockingInCurrentStores;
                    StockTransferMasters.ReservedStock =  model.ReservedStock;
                    StockTransferMasters.FreeStock =  model.FreeStock;

                    var format = "dd/MM/yyyy";
                    DateTime InvoiceRef = DateTime.ParseExact(model.InvoiceRef, format, CultureInfo.InvariantCulture);
                    DateTime InvoiceDate = DateTime.ParseExact(model.InvoiceDate, format, CultureInfo.InvariantCulture);
                    StockTransferMasters.InvoiceRef =   InvoiceRef;
                    StockTransferMasters.InvoiceDate =  InvoiceDate;
                    StockTransferMasters.CreatedBy =  model.CreatedBy;
                    StockTransferMasters.UpdatedBy =  model.UpdatedBy;
                    StockTransferMasters.CreatedDate =  model.CreatedDate;
                    StockTransferMasters.UpdatedDate =  model.UpdatedDate;
                    StockTransferMasters.CreatedDate = DateTime.Now;
                    stockManager.Post(StockTransferMasters);
                }
                else
                {
                    return Json(StockTransferMasters, JsonRequestBehavior.AllowGet);
                }

            }
            return Json(StockTransferMasters, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Update(StockTransferModel model)
        {
            StockTransferMaster StockTransferMasters = new StockTransferMaster();
            StockTransferMaster StockTransferMaster = new StockTransferMaster();
            if (ModelState.IsValid)
            {
                StockTransferManager stockManager = new StockTransferManager();
                StockTransferMaster = stockManager.GetStockTransferMasterId(model.StockTransferID);
                if (StockTransferMaster != null)
                {
                    StockTransferMasters.StockTransferID = model.StockTransferID;
                    StockTransferMasters.GrnTypeMasterId = model.GrnTypeMasterId;
                    StockTransferMasters.GRNNo = model.GRNNo;
                    StockTransferMasters.IssuedTo = model.IssuedTo;
                    StockTransferMasters.StoreMasterId = model.StoreMasterId;
                    StockTransferMasters.TransportDetails = model.TransportDetails;
                    StockTransferMasters.Remarks = model.Remarks;
                    StockTransferMasters.Rate = model.Rate;
                    StockTransferMasters.Value = model.Value;
                    StockTransferMasters.PartyDCNo = model.PartyDCNo;
                    StockTransferMasters.MatCategoryId = model.MatCategoryId;
                    StockTransferMasters.MatGroupId = model.MatGroupId;
                    StockTransferMasters.ColourId = model.ColourId;
                    StockTransferMasters.Quantity = model.Quantity;
                    StockTransferMasters.ClosingStockInAllStores = model.ClosingStockInAllStores;
                    StockTransferMasters.ClosingStockingInCurrentStores = model.ClosingStockingInCurrentStores;
                    StockTransferMasters.ReservedStock = model.ReservedStock;
                    StockTransferMasters.FreeStock = model.FreeStock;

                    var format = "dd/MM/yyyy";
                    DateTime InvoiceRef = DateTime.ParseExact(model.InvoiceRef, format, CultureInfo.InvariantCulture);
                    DateTime InvoiceDate = DateTime.ParseExact(model.InvoiceDate, format, CultureInfo.InvariantCulture);
                    
                    StockTransferMasters.InvoiceRef = InvoiceRef;
                    StockTransferMasters.InvoiceDate =InvoiceDate;
                  
                    stockManager.Put(StockTransferMasters);
                }
                else
                {
                    return Json(StockTransferMasters, JsonRequestBehavior.AllowGet);
                }

            }
            return Json(StockTransferMasters, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int StockTransferID)
        {
             StockTransferMaster stockMaster = new  StockTransferMaster();
            string status = "";
            StockTransferManager stockManager = new StockTransferManager();
            stockMaster = stockManager.GetStockTransferMasterId(StockTransferID);
            if (stockMaster != null)
            {
                status = "Success";
                stockManager.Delete(stockMaster.StockTransferID);
            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Helper Method
        public ActionResult Search(string filter)
        {
            List<StockTransferMaster> stockMasterList = new List< StockTransferMaster>();
            StockTransferManager stockManager = new StockTransferManager();
            stockMasterList = stockManager.Get();
            stockMasterList = stockMasterList.Where(x => x.GRNNo.ToLower().Contains(filter.ToLower()) || x.TransportDetails.ToLower().Contains(filter.ToLower())).ToList();
            StockTransferModel sm = new StockTransferModel();

MMS.Web/Views/StockTransferMaster/Partial/StockTransferMasterGrid.cshtml
@model MMS.Web.Models.StockTransferModel.StockTransferModel
@using MMS.Core.Entities;
@{
    MMS.Repository.Managers.GRNTypeManager grnTypeManager = new MMS.Repository.Managers.GRNTypeManager();
    GrnTypeMaster grnMaster = new GrnTypeMaster();

    MMS.Repository.Managers.StoreMasterManager storeManager = new MMS.Repository.Managers.StoreMasterManager();
    StoreMaster storeMaster = new StoreMaster();

    MMS.Repository.Managers.MaterialCategoryManager materialCategoryManager = new MMS.Repository.Managers.MaterialCategoryManager();
    MaterialCategoryMaster matCatMaster = new MaterialCategoryMaster();

    MMS.Repository.Managers.MaterialGroupManager  materialGroupManager = new MMS.Repository.Managers.MaterialGroupManager();
    materialgroupmaster matGrpMaster = new materialgroupmaster();

    MMS.Repository.Managers.ColorManager colorManager = new MMS.Repository.Managers.ColorManager();
    ColorMaster colorMaster = new ColorMaster();
}
 
<div class="veh-tablewrap">
    <div class="veh-tablecont">
        <div id="sortMsg" style="text-align: center; color: Red;"></div>

        <table class="veh-table" id="empTable">
            <thead>
                <tr class="color-code-top-btn">
                    <td colspan="13">
                        <input type="text" id="SeaarchID" placeholder="Search.." /><input type="button" value="Add" onclick="Add()">
                        <input type="button" value="Search" onclick="    Search()"></td>
                </tr>
                <tr>
                     <th class="veh-1"> Si. NO
                    </th>
                    <th class="veh-2">Issued Type
                    </th>
                    <th class="veh-2">DC/GRN No
                    </th>
                    <th class="veh-3"> Issued To/From
                    </th>
                    <th class="veh-4">Stores
                    </th>
                    <th class="veh-5">Material Category
                    </th>
                    <th class="veh-6">Material Group
                    </th>  
                        <th class="veh-7">Colour
                    </th>                                 
                        <th class="veh-8">Quantity
                    </th>
                    <th class="veh-9">Edit/Delete
                    </th>
                </tr>
            </thead>
            @if (Model.StockTransferMasterList != null && Model.StockTransferMasterList.Count > 0)
            {
                int count = 1;
                <tbody>
                   
                    @foreach (var stock in Model.StockTransferMasterList)
                    {
                        grnMaster = grnTypeManager.GetIssueTypeMasterId(stock.GrnTypeMasterId);
                        storeMaster = storeManager.GetStoreMasterId(stock.StoreMasterId);
                        matCatMaster = materialCategoryManager.GetMaterialCategoryMaster(stock.MatCategoryId);
                        matGrpMaster = materialGroupManager.GetmaterialgroupmasterId(stock.MatGroupId);
                        colorMaster = colorManager.GetColorMasterID(stock.ColourId);
                        
                        <tr>
                            <td class="veh-1" onclick="">@count</td>
                            <td class="veh-2">@grnMaster.IssueType</td>
                            <td class="veh-3">@stock.GRNNo</td>
                            <td class="veh-4">@stock.IssuedTo</td>
                            <td class="veh-5">@storeMaster.StoreName</td>
                            <td class="veh-6">@matCatMaster.CategoryName</td>    
                            <td class="veh-7">@matGrpMaster.GroupName</td>   
                            <td class="veh-8">@colorMaster.Color</td>  
                            <td class="veh-9">@stock.Quantity</td>    
                                                   
                            <td class="veh-7 edit-del-wrap">
                                <a href="javascript:void(0)" onclick="Edit('@stock.StockTransferID')" class="watchlist-edit" title="Edit"></a>
                                <a href="javascript:void(0)" id="DeleteVehicleWatchList" onclick="Delete('@stock.StockTransferID')" class="watchlist-delete" title="Delete"></a>

                            </td>
                        </tr>
                        count++;
                    }


                </tbody>
                <tfoot class="footer-pager">
                    <tr>
                        <td colspan="4">
                            <div id="pager">
                                <form>
                                    <img src="@Url.Content("~/Content/images/first.png")" class="first" />
                                    <img src="@Url.Content("~/Content/images/prev.png")" class="prev" />
                                    <input type="text" class="pagedisplay" />
                                    <img src="@Url.Content("~/Content/images/next.png")" class="next" />
                                    <img src="@Url.Content("~/Content/images/last.png")" class="last" />
                                    <select class="pagesize">
                                        <option selected="selected" value="5">5</option>
                                        <option value="10">10</option>
                                        <option value="20">20</option>
                                        <option value="30">30</option>
                                        <option value="40">40</option>
                                    </select>
                                </form>
                            </div>

                        </td>

                    </tr>

                </tfoot>
                
            }
        </table>
        @if (Model.StockTransferMasterList != null && Model.StockTransferMasterList.Count == 0)
        {
            <div style="color: red; font-size: 16px; text-align: center; width: 100%;">No Records Found</div>
        }
    </div>

    <div id="EditColorPartial">
        @Html.Partial("Partial/StockTransferMasterDetails", Model)
    </div>


</div>


<script>
    function Search() {
        $.ajax({
            type: "POST",
            url: ' @Url.Action("Search", "StockTransferMaster")',
            data: { filter: $('#SeaarchID').val() },
            success: function (data) {
     
                $(".veh-tablewrap").html(data);
                $(".veh-tablewrap").show();
                $('#DivShow').hide();
                $('#EditColorPartial').hide();
            }
        });
    }
    
    function Cancel() {
      
        location.reload();
    }
    function Add() {
        $('.veh-tablecont').hide();
        $.ajax({
            type: "POST",
            url: ' @Url.Action("StockTransferMasterDetails", "StockTransferMaster")',
            data: { StockTransferID: 0 },
            success: function (data) {
                $("#EditColorPartial").html(data);
                $("#EditColorPartial").show();
            }
        });
        $("#EditColorPartial").show();
    }
    function Edit(arg) {
        $('.veh-tablecont').hide();
        $.ajax({
            type: "POST",
            url: ' @Url.Action("StockTransferMasterDetails", "StockTransferMaster")',
            data: { StockTransferID: arg },
            success: function (data) {
                $("#EditColorPartial").html(data);
                $("#EditColorPartial").show();
            }
        });
        $("#EditColorPartial").show();
    }
    function Delete(arg) {
        var answer = confirm("Are you sure want to delete?");
        if (answer) {
            $.ajax({
                type: 'POST',
                url: ' @Url.Action("Delete", "StockTransferMaster")',
                data: { StockTransferID: arg },
                success: function (data) {
                    if (data == "Success") {
                        alert('Deleted Successfully.');
                        location.href = "/StockTransferMaster/StockTransferMaster";
                        return false;
                    }
                    else {
                        alert('deletion failed.');
                    }

                },
                error: function (ex) {
                    alert('This Color Already Exist in the database.');
                }
            });
        }
        else {
            return false;
        }
    }


</script>