MMS.Web/Controllers/AgentMasterController.cs
using MMS.Common;
using MMS.Core.Entities;
using MMS.Repository.Managers;
using MMS.Web.Models.AgentMasterModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MMS.Web.Controllers
{
    [CustomFilter]
    public class AgentMasterController : Controller
    {
        #region Accounts View

        [HttpGet]
        public ActionResult AgentMaster()
        {
            AgentMasterModel vm = new AgentMasterModel();
            return View(vm);
        }
        public ActionResult AgentMasterGrid()
        {
            AgentMasterModel vm = new AgentMasterModel();
            AgentManager agentManager = new AgentManager();
            vm.AgentMastetlist = agentManager.Get();

            return PartialView("Partial/AgentMasterGrid", vm);
        }
        [HttpPost]
        public ActionResult AgentMasterDetails(int AgentMasterId)
        {
            AgentManager agentManager = new AgentManager();
            CommisionCritiriaManager commisionCritirialManager = new CommisionCritiriaManager();
            AgentMaster agentMaster = new AgentMaster();
            AgentMasterModel model = new AgentMasterModel();
            agentMaster = agentManager.GetAgentMasterId(AgentMasterId);
            int ID = MMS.Web.ExtensionMethod.HtmlHelper.getAgentCodeId();
         

            if (agentMaster != null)
            {
                model.AgentMasterId = agentMaster.AgentMasterId;
                model.AgentFullName = agentMaster.AgentFullName;
                model.AgentShortName = agentMaster.AgentShortName;
                model.Currency = agentMaster.Currency;
                model.CommisionCriteriaId = agentMaster.CommisionCriteriaId;
                model.AddressLine1 = agentMaster.AddressLine1;
                model.AddressLine2 = agentMaster.AddressLine2;
                model.AddressLine3 = agentMaster.AddressLine3;
                model.Pincode = agentMaster.Pincode;
                model.CreatedDate = agentMaster.CreatedDate;
                model.UpdatedDate = agentMaster.UpdatedDate;
                model.CreatedBy = agentMaster.CreatedBy;
                model.UpdatedBy = agentMaster.UpdatedBy;
                model.ContactPerson = agentMaster.ContactPerson;
                model.MobileNo = agentMaster.MobileNo;
                model.EmailID = agentMaster.EmailID;
                model.CountryMasterId = agentMaster.CountryMasterId;
                model.CommisionPercentage = agentMaster.CommisionPercentage;
                model.CommisionCriteriaList = commisionCritirialManager.Get();
            }
            if (model.AgentMasterId != 0)
            {
                model.AgentCode = agentMaster.AgentCode;
            }
            else 
            {
                ID++;
                model.AgentCode = "AGT" + ID;
            }
            return PartialView("Partial/AgentMasterDetails", model);
        }

        public ActionResult InternalModelDetail(int CommisionCriteriaId)
        {
            CommisionCritiriaManager commissionCriteriaManager = new CommisionCritiriaManager();
            CommisionCriteria commissionCriteriaMaster = new CommisionCriteria();
            commissionCriteriaMaster = commissionCriteriaManager.GetCommisionCriteriaId(CommisionCriteriaId);
            return Json(new { CommissionPercent = commissionCriteriaMaster.CommisionPercent }, JsonRequestBehavior.AllowGet);

        }

        #endregion

        #region Curd Operation
        [HttpPost]
        public ActionResult AgentMaster(AgentMasterModel model)
        {
            AgentMaster AgentMasters = new AgentMaster();
            if (ModelState.IsValid)
            {
                AgentMaster agentMaster = new AgentMaster();
                AgentManager agentManager = new AgentManager();

                int ID = MMS.Web.ExtensionMethod.HtmlHelper.getAgentCodeId();
                ID++;

                agentMaster = agentManager.GetAgentFullName(model.AgentFullName);
                if (agentMaster == null)
                {
                    AgentMasters.AgentCode = "AGT" + ID;
                    AgentMasters.AgentFullName = model.AgentFullName;
                    AgentMasters.AgentShortName = model.AgentShortName;
                    AgentMasters.Currency = model.Currency;
                    AgentMasters.CommisionCriteriaId = model.CommisionCriteriaId;
                    AgentMasters.AddressLine1 = model.AddressLine1;
                    AgentMasters.AddressLine2 = model.AddressLine2;
                    AgentMasters.AddressLine3 = model.AddressLine3;
                    AgentMasters.Pincode = model.Pincode;
                    AgentMasters.CreatedDate = DateTime.Now;
                    AgentMasters.ContactPerson = model.ContactPerson;
                    AgentMasters.MobileNo = model.MobileNo;
                    AgentMasters.EmailID = model.EmailID;
                    AgentMasters.CountryMasterId = model.CountryMasterId;
                    AgentMasters.CommisionPercentage = model.CommisionPercentage;
                    agentManager.Post(AgentMasters);
                }
                else if(agentMaster != null && agentMaster.AgentFullName == model.AgentFullName && model.AgentMasterId == 0)
                {
                    agentMaster.AgentMasterId = 0;
                    return Json(agentMaster, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(AgentMasters, JsonRequestBehavior.AllowGet);
                }

            }
            return Json(AgentMasters, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Update(AgentMasterModel model)
        {
            AgentMaster AgentMasters = new AgentMaster();
            if (ModelState.IsValid)
            {
                AgentMaster agentMaster = new AgentMaster();
                AgentManager agentManager = new AgentManager();
                agentMaster = agentManager.GetAgentMasterId(model.AgentMasterId);
                if (agentMaster != null)
                {
                    AgentMasters.AgentMasterId = model.AgentMasterId;
                    AgentMasters.AgentCode = model.AgentCode;
                    AgentMasters.AgentFullName = model.AgentFullName;
                    AgentMasters.AgentShortName = model.AgentShortName;
                    AgentMasters.Currency = model.Currency;
                    AgentMasters.CommisionCriteriaId = model.CommisionCriteriaId;
                    AgentMasters.AddressLine1 = model.AddressLine1;
                    AgentMasters.AddressLine2 = model.AddressLine2;
                    AgentMasters.AddressLine3 = model.AddressLine3;
                    AgentMasters.Pincode = model.Pincode;
                    AgentMasters.CreatedDate = agentMaster.CreatedDate;
                    AgentMasters.UpdatedDate = DateTime.Now;
                    AgentMasters.ContactPerson = model.ContactPerson;
                    AgentMasters.MobileNo = model.MobileNo;
                    AgentMasters.EmailID = model.EmailID;
                    AgentMasters.CountryMasterId = model.CountryMasterId;
                    AgentMasters.CommisionPercentage = model.CommisionPercentage;
                    agentManager.Put(AgentMasters);
                }
                else
                {
                    return Json(AgentMasters, JsonRequestBehavior.AllowGet);
                }

            }
            return Json(AgentMasters, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int AgentMasterId)
        {
            AgentMaster agentMaster = new AgentMaster();
            string status = "";
            AgentManager agentManager = new AgentManager();
            agentMaster = agentManager.GetAgentMasterId(AgentMasterId);
            if (agentMaster != null)
            {
                status = "Success";
                agentManager.Delete(agentMaster.AgentMasterId);
            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Helper Method
        public ActionResult Search(string filter)
        {
            List<AgentMaster> agentmasterList = new List<AgentMaster>();
            AgentManager agentManager = new AgentManager();
            agentmasterList = agentManager.Get();
            agentmasterList = agentmasterList.Where(x => x.AgentFullName.ToLower().Trim().Contains(filter.ToLower().Trim()) || x.AgentCode.ToLower().Trim().Contains(filter.ToLower().Trim()) || x.AgentShortName.ToLower().Trim().Contains(filter.ToLower().Trim())).ToList();
            AgentMasterModel vm = new AgentMasterModel();
            vm.AgentMastetlist = agentmasterList;
            return PartialView("Partial/AgentMasterGrid", vm);
        }
        #endregion


    }
}

MMS.Web/Views/AgentMaster/Partial/AgentMasterGrid.cshtml
@model MMS.Web.Models.AgentMasterModel.AgentMasterModel
@using MMS.Repository.Managers
@using MMS.Core.Entities
@{
    CommisionCritiriaManager manager = new CommisionCritiriaManager();
    CommisionCriteria commisionCriteria = new CommisionCriteria();


    CurrencyManager currencyManager = new CurrencyManager();
    CurrencyMaster currencyMaster = new CurrencyMaster();

}
<div class="veh-tablewrap">
    <div class="veh-tablecont">
        <div id="sortMsg" style="text-align: center; color: Red;"></div>
        <div class="table-responsive table-td-padding padding-lr-6px table-row-bg" style="overflow: auto;">
            <table class="veh-table table" id="empTable">
                <thead>
                    <tr class="color-code-top-btn">
                        <td colspan="13">
                            <input type="text" id="SeaarchID" placeholder="Search.." /><input type="button" value="Add" onclick="Add()">
                            <input type="button" value="Search" onclick="    Search()">
                        </td>
                    </tr>
                    <tr>
                        <th class="veh-1">
                            Si. No
                        </th>
                        <th class="veh-1">
                            AgentCode
                        </th>
                        <th class="veh-2">
                            AgentFullName
                        </th>
                        <th class="veh-3">
                            AgentShortName
                        </th>
                        <th class="veh-4">
                            Currency
                        </th>
                        <th class="veh-5">
                            CommissionCritiriaName
                        </th>
                        <th class="veh-6">
                            Commission%
                        </th>
                        <th class="veh-6">
                            Edit/Delete
                        </th>
                    </tr>
                </thead>
                @if (Model.AgentMastetlist != null && Model.AgentMastetlist.Count > 0)
                {
                    int count = 1;
                    <tbody>

                        @foreach (var AgentMaste in Model.AgentMastetlist)
                    {
                        currencyMaster = currencyManager.GetCurrentMasterId(AgentMaste.Currency);
                        commisionCriteria = manager.GetCommisionCriteriaId(AgentMaste.CommisionCriteriaId);
                        if (commisionCriteria != null)
                        {
                            Model.CommisionCritiriaName = commisionCriteria.CommisionName;
                            Model.CommisionPercentage = commisionCriteria.CommisionPercent;
                        }
                <tr>
                    <td class="veh-1">@count</td>
                    <td class="veh-1" onclick="">@AgentMaste.AgentCode</td>
                    <td class="veh-2">@AgentMaste.AgentFullName</td>
                    <td class="veh-3">@AgentMaste.AgentShortName</td>
                    <td class="veh-4">@currencyMaster.LongForm</td>
                    <td class="veh-5">@Model.CommisionCritiriaName</td>
                    <td class="veh-6">@Model.CommisionPercentage</td>
                    <td class="veh-1 edit-del-wrap">
                        <a href="javascript:void(0)" onclick="Edit('@AgentMaste.AgentMasterId')" class="watchlist-edit" title="Edit"></a>
                        <a href="javascript:void(0)" id="DeleteVehicleWatchList" onclick="Delete('@AgentMaste.AgentMasterId')" class="watchlist-delete" title="Delete"></a>

                    </td>
                </tr>
                        count++;
                    }


                    </tbody>
                    <tfoot class="footer-pager">
                        <tr>
                            <td colspan="4">
                                <div id="pager">
                                    <form>
                                        <img src="@Url.Content("~/Content/images/first.png")" class="first" />
                                        <img src="@Url.Content("~/Content/images/prev.png")" class="prev" />
                                        <input type="text" class="pagedisplay" />
                                        <img src="@Url.Content("~/Content/images/next.png")" class="next" />
                                        <img src="@Url.Content("~/Content/images/last.png")" class="last" />
                                        <select class="pagesize">
                                            <option selected="selected" value="5">5</option>
                                            <option value="10">10</option>
                                            <option value="20">20</option>
                                            <option value="30">30</option>
                                            <option value="40">40</option>
                                        </select>
                                    </form>
                                </div>

                            </td>

                        </tr>

                    </tfoot>
                }
            </table>
            @if (Model.AgentMastetlist != null && Model.AgentMastetlist.Count == 0)
            {
                <div style="color: red; font-size: 16px; text-align: center; width: 100%;">No Records Found</div>
            }
        </div>
    </div>

    <div id="EditColorPartial">
        @Html.Partial("Partial/AgentMasterDetails", Model)
    </div>


</div>


<script>
    $(document).ajaxStart(function () {
        $(".loader-overlay").css("display", "block");
    });

    $(document).ajaxComplete(function () {
        $(".loader-overlay").css("display", "none");
    });
    $(window).load(function () {
        $('.loader-overlay').fadeOut('fast');
    });
    function Search() {
        $.ajax({
            type: "POST",
            url: ' @Url.Action("Search", "AgentMaster")',
            data: { filter: $('#SeaarchID').val() },
            success: function (data) {
                //console.log(data);
                //$('#DivShow').hide();
                $(".veh-tablewrap").html(data);
                $(".veh-tablewrap").show();
                $('#DivShow').hide();
                $('#EditColorPartial').hide();
            }
        });
    }
    
    function Cancel() {
        //$('#EditColorPartial').hide()
        location.reload();
    }
    function Add() {
             $.ajax({
            type: "POST",
            url: ' @Url.Action("AgentMasterDetails", "AgentMaster")',
            data: { AgentMasterId: 0 },
            success: function (data) {
                $('.veh-tablecont').hide();
                $("#EditColorPartial").html(data);
                $("#EditColorPartial").show();
            }
        });

    }
    function Edit(arg) {
        $.ajax({
            type: "POST",
            url: ' @Url.Action("AgentMasterDetails", "AgentMaster")',
            data: { AgentMasterId: arg },
            success: function (data) {
                $('.veh-tablecont').hide();
                $("#EditColorPartial").html(data);
                $("#EditColorPartial").show();
            }
        });

    }
    function Delete(arg) {
        var answer = confirm("Are you sure want to delete?");
        if (answer) {
            $.ajax({
                type: 'POST',
                url: ' @Url.Action("Delete", "AgentMaster")',
                data: { AgentMasterId: arg },
                success: function (data) {
                    if (data == "Success") {
                        alert('Deleted Successfully.');
                        location.href = "/AgentMaster/AgentMaster";
                        return false;
                    }
                    else {
                        alert('deletion failed.');
                    }

                },
                error: function (ex) {
                    alert('This Color Already Exist in the database.');
                }
            });
        }
        else {
            return false;
        }
    }


</script>