MMS.Web/Controllers/StageMasterController.cs
using MMS.Common;
using MMS.Core.Entities;
using MMS.Repository.Managers;
using MMS.Web.Models.StageMaser;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace MMS.Web.Controllers
{
    [CustomFilter]
    public class StageMasterController : Controller
    {
        #region Accounts View

        [HttpGet]
        public ActionResult StageMaster()
        {
            StageMasterModel vm = new StageMasterModel();
            return View(vm);
        }
        public ActionResult StageMaserGrid()
        {
            StageMasterModel vm = new StageMasterModel();
            StageMasterManager stageMasterManager = new StageMasterManager();
            vm.StageMasterList = stageMasterManager.Get();

            return PartialView("Partial/StageMaserGrid", vm);
        }
        [HttpPost]
        public ActionResult StageMasteDetails(int StageMasterId)
        {
            StageMasterManager stageMasterManager = new StageMasterManager();
            StageMaster stageMaster = new StageMaster();
            StageMasterModel model = new StageMasterModel();
            stageMaster = stageMasterManager.GetStageMasterId(StageMasterId);

            int ID = MMS.Web.ExtensionMethod.HtmlHelper.getStageMasterCodeId();
            ID++;

            if (stageMaster != null)
            {
                model.StageMasterId = stageMaster.StageMasterId;
                model.OrderType = stageMaster.OrderType;
                model.IsInspection = stageMaster.IsInspection;
                model.ProcessCode = stageMaster.ProcessCode;
                model.StageCode = stageMaster.StageCode;
                model.StageName = stageMaster.StageName;
                model.SubStage = stageMaster.SubStage;
                model.CreatedDate = stageMaster.CreatedDate;
                model.UpdatedDate = stageMaster.UpdatedDate;
                model.CreatedBy = stageMaster.CreatedBy;
                model.UpdatedBy = stageMaster.UpdatedBy;
            }
            if (model.StageMasterId != 0)
            {
                model.StageCode = stageMaster.StageCode;
            }
            else
            {
                model.StageCode = "SM" + ID;
            }
            return PartialView("Partial/StageMasteDetails", model);
        }
        #endregion

        #region Curd Operation
        [HttpPost]
        public ActionResult StageMaster(StageMasterModel model)
        {
            StageMaster StageMasters = new StageMaster();
            StageMaster stageMaster = new StageMaster();
            StageMasterManager stageMasterManager = new StageMasterManager();
            stageMaster = stageMasterManager.GetStageName(model.StageName);
            if (stageMaster == null && model.StageMasterId == 0)
            {
                int ID = MMS.Web.ExtensionMethod.HtmlHelper.getStageMasterCodeId();
                ID++;

                StageMasters.OrderType = model.OrderType;
                StageMasters.IsInspection = model.IsInspection;
                StageMasters.ProcessCode = model.ProcessCode;
                StageMasters.StageCode = "SM" + ID;
                StageMasters.StageName = model.StageName;
                StageMasters.SubStage = model.SubStage;
                StageMasters.Sequence = model.Sequence;
                StageMasters.CreatedDate = DateTime.Now;
                stageMasterManager.Post(StageMasters);
                ID++;
                model.StageCode = "SM" + ID;
                model.StageName = "";
                model.SubStage = "";
                model.StageMasterList = stageMasterManager.GetStageProcessId(model.ProcessCode);
                ID++;
                //  return Json(new { items = StageMasters }, JsonRequestBehavior.AllowGet);
                return PartialView("~/Views/Jobwork/Job_Master/StageMaster/Partial/Stagegrid_sequence.cshtml", model);

            }
            if ( model.StageMasterId !=0)
            {
                StageMasters.StageMasterId = model.StageMasterId;
                StageMasters.OrderType = model.OrderType;
                StageMasters.IsInspection = model.IsInspection;
                StageMasters.ProcessCode = model.ProcessCode;
                StageMasters.StageCode = model.StageCode;
                StageMasters.StageName = model.StageName;
                StageMasters.SubStage = model.SubStage;
                StageMasters.Sequence = model.Sequence;
                stageMasterManager.Put(StageMasters);

                int ID = MMS.Web.ExtensionMethod.HtmlHelper.getStageMasterCodeId();
                ID++;
                model.StageCode = "SM" + ID;
                model.StageName = "";
                model.SubStage = "";
                model.StageMasterList = stageMasterManager.GetStageProcessId(model.ProcessCode);
                ID++;
                //  return Json(new { items = StageMasters }, JsonRequestBehavior.AllowGet);
                return PartialView("~/Views/Jobwork/Job_Master/StageMaster/Partial/Stagegrid_sequence.cshtml", model);
            }
            else if (stageMaster != null && stageMaster.StageName == model.StageName)
                {
                    StageMasters.StageMasterId = 0;
                    return Json(StageMasters, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(StageMasters, JsonRequestBehavior.AllowGet);
                }
                           
           
            return Json(StageMasters, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Update(StageMasterModel model)
        {
            StageMaster StageMasters = new StageMaster();
            StageMaster stageMaster = new StageMaster();
            StageMasterManager stageMasterManager = new StageMasterManager();
            stageMaster = stageMasterManager.GetStageMasterId(model.StageMasterId);
            if (stageMaster != null)
            {
                StageMasters.StageMasterId = model.StageMasterId;
                StageMasters.OrderType = model.OrderType;
                StageMasters.IsInspection = model.IsInspection;
                StageMasters.ProcessCode = model.ProcessCode;
                StageMasters.StageCode = model.StageCode;
                StageMasters.StageName = model.StageName;
                StageMasters.SubStage = model.SubStage;
                StageMasters.Sequence = model.Sequence;
                StageMasters.UpdatedDate = DateTime.Now;
                StageMasters.CreatedBy = stageMaster.CreatedBy;
                StageMasters.UpdatedBy = stageMaster.UpdatedBy;
                stageMasterManager.Put(StageMasters);
            }
            return Json(StageMasters, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Update_stageseq(StageMasterModel model)
        {
            StageMaster StageMasters = new StageMaster();
            StageMasterManager stageMasterManager = new StageMasterManager();
            string[] intArray = model.OrderType.Split(',');


            foreach (var item in intArray)
            {
               string[] sizearry = item.Split(';');
                if (sizearry[0] != "," && sizearry[1] != "," && sizearry[1] != ",")
                {
                    string a = sizearry[0];
                string b = sizearry[1];
                
                    StageMasters.Sequence = Convert.ToInt32(a);
                    StageMasters.StageMasterId = Convert.ToInt32(b);
                    stageMasterManager.Putsedquence(StageMasters);
                }
            }
            //StageMaster StageMasters = new StageMaster();
            //StageMaster stageMaster = new StageMaster();
            //StageMasterManager stageMasterManager = new StageMasterManager();
            //stageMaster = stageMasterManager.GetStageMasterId(model.StageMasterId);
            //if (stageMaster != null)
            //{
            //    StageMasters.StageMasterId = model.StageMasterId;
            //    StageMasters.OrderType = model.OrderType;
            //    StageMasters.IsInspection = model.IsInspection;
            //    StageMasters.ProcessCode = model.ProcessCode;
            //    StageMasters.StageCode = model.StageCode;
            //    StageMasters.StageName = model.StageName;
            //    StageMasters.SubStage = model.SubStage;
            //    StageMasters.Sequence = model.Sequence;
            //    StageMasters.UpdatedDate = DateTime.Now;
            //    StageMasters.CreatedBy = stageMaster.CreatedBy;
            //    StageMasters.UpdatedBy = stageMaster.UpdatedBy;
            //    stageMasterManager.Put(StageMasters);
            //}
            return Json(StageMasters, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int StageMasterId)
        {
            StageMaster stageMaster = new StageMaster();
            string status = "";
            StageMasterManager stageMasterManager = new StageMasterManager();
            stageMaster = stageMasterManager.GetStageMasterId(StageMasterId);
            if (stageMaster != null)
            {
                status = "Success";
                stageMasterManager.Delete(stageMaster.StageMasterId);
            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Helper Method
        public ActionResult Search(string filter)
        {
            List<StageMaster> stageMasterList = new List<StageMaster>();
            StageMasterManager stageMasterManager = new StageMasterManager();
            stageMasterList = stageMasterManager.Get();
            stageMasterList = stageMasterList.Where(x => x.StageName.ToLower().Trim().Contains(filter.ToLower().Trim()) || x.StageCode.ToLower().Trim().Contains(filter.ToLower().Trim()) || x.OrderType.ToLower().Trim().Contains(filter.ToLower().Trim())).ToList();

MMS.Web/Views/StageMaster/StageMaster.cshtml
@{
    ViewBag.Title = "Material Category";
    Layout = "~/Views/Shared/_Layout.cshtml";

    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/FormStyle.css" rel="stylesheet" />

}

<script>
    $(document).ready(function () {
        $(document).ajaxStart(function () {
            $(".loader-overlay").css("display", "block");
        });

        $(document).ajaxComplete(function () {
            $(".loader-overlay").css("display", "none");
        });
        $(window).load(function () {
            $('.loader-overlay').fadeOut('fast');
        });

        $("#EditColorPartial").hide();

    });
    function Save() {
        if ($('#ProcessCode').val() == "") {
            alert("Please Enter Process Code.")
            $('#ProcessCode').css('border-color', 'red');
            $('#ProcessCode').focus();
            return false;
        }
        else {
            $('#ProcessCode').css('border-color', '');
        }
        if ($('#OrderType').val() == "") {
            alert("Please Enter Order Type.")
            $('#OrderType').css('border-color', 'red');
            $('#OrderType').focus();
            return false;
        }
        else {
            $('#OrderType').css('border-color', '');
        }
        if ($('#StageCode').val() == "") {
            alert("Please Enter Stage Code.")
            $('#StageCode').css('border-color', 'red');
            $('#StageCode').focus();
            return false;
        }
        else {
            $('#StageCode').css('border-color', '');
        }
        if ($('#StageName').val() == "") {
            alert("Please Enter Stage Name.")
            $('#StageName').css('border-color', 'red');
            $('#StageName').focus();
            return false;
        }
        else {
            $('#StageName').css('border-color', '');
        }
        if ($('#SubStage').val() == "") {
            alert("Please Enter SubStage.")
            $('#SubStage').css('border-color', 'red');
            $('#SubStage').focus();
            return false;
        }
        else {
            $('#SubStage').css('border-color', '');
        }
        $.ajax({
            type: 'POST',
            url: '/StageMaster/StageMaster',
            data: {
                ProcessCode: $('#ProcessCode').val(),
                OrderType: $('#OrderType').val(),
                StageCode: $('#StageCode').val(),
                StageName: $('#StageName').val(),
                SubStage: $('#SubStage').val(),
                Sequence: $('#Sequence').val(),
                IsInspection: $('#IsInspection').is(":checked"),
            },
            success: function (data) {
                if (data.StageMasterId != "" || data.StageMasterId != 0) {
                    alert('Saved Successfully.');
                    location.href = "/StageMaster/StageMaster";
                    return false;
                }
                else if (data.StageMasterId == 0 && data.StageName != "") {
                    alert('Already Exist in the database.');
                    return false;
                }
                else {
                    alert('Save process Failed.');
                    location.href = "/StageMaster/StageMaster";
                    return false;
                }

            },
            error: function (ex) {
                alert('Already Exist in the database.');
            }
        });
    }
    function Update(arg) {
        if ($('#ProcessCode').val() == "") {
            alert("Please Enter Process Code.")
            $('#ProcessCode').css('border-color', 'red');
            $('#ProcessCode').focus();
            return false;
        }
        else {
            $('#ProcessCode').css('border-color', '');
        }
        if ($('#OrderType').val() == "") {
            alert("Please Enter Order Type.")
            $('#OrderType').css('border-color', 'red');
            $('#OrderType').focus();
            return false;
        }
        else {
            $('#OrderType').css('border-color', '');
        }
        if ($('#StageCode').val() == "") {
            alert("Please Enter Stage Code.")
            $('#StageCode').css('border-color', 'red');
            $('#StageCode').focus();
            return false;
        }
        else {
            $('#StageCode').css('border-color', '');
        }
        if ($('#StageName').val() == "") {
            alert("Please Enter Stage Name.")
            $('#StageName').css('border-color', 'red');
            $('#StageName').focus();
            return false;
        }
        else {
            $('#StageName').css('border-color', '');
        }
        if ($('#SubStage').val() == "") {
            alert("Please Enter SubStage.")
            $('#SubStage').css('border-color', 'red');
            $('#SubStage').focus();
            return false;
        }
        else {
            $('#SubStage').css('border-color', '');
        }
        $.ajax({
            type: 'POST',
            url: '/StageMaster/Update',
            data: {
                StageMasterId: $('#StageMasterId').val(),
                ProcessCode: $('#ProcessCode').val(),
                OrderType: $('#OrderType').val(),
                StageCode: $('#StageCode').val(),
                StageName: $('#StageName').val(),
                SubStage: $('#SubStage').val(),
                Sequence: $('#Sequence').val(),
                IsInspection: $('#IsInspection').is(":checked"),
            },
            success: function (data) {
                if (data.StageMasterId != "" || data.StageMasterId != 0) {
                    alert('Updated Successfully.');
                    location.href = "/StageMaster/StageMaster";
                    return false;
                }
                else {
                    alert('Updation failed.');
                    location.href = "/StageMaster/StageMaster";
                    return false;
                }

            },
            error: function (ex) {
                alert('Already Exist in the database.');
            }
        });
    }
</script>
<h2 class="content-title">Stage Master</h2>
<div style="width: 100%; float: left;">

    <div class="loader-overlay" style="position:fixed;left:0;right:0;top:0;bottom:0;margin:auto;width:100%;height:100%;background:rgba(0,0,0,0.8);z-index:99;">
        <div id="spinner" style="position:relative;height:64px;width:64px;margin:auto;top:50%;">
            <img src="~/Content/Images/round.gif" id="imgLoading" alt="Loading..." />
        </div>
    </div>
    <div id="tabVehicleWatchList">
        @Html.Action("StageMaserGrid", "StageMaster")
    </div>
</div>