MMS.Web/Controllers/SizeRangedetailController.cs
using MMS.Common;
using MMS.Core.Entities;
using MMS.Repository.Managers;
using MMS.Web.Models.SizeRangeDetailsModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MMS.Web.Controllers
{
    [CustomFilter]
    public class SizeRangedetailController : Controller
    {
        #region Accounts View

        [HttpGet]
        public ActionResult SizeRangedetail()
        {
            SizeRangeDetails vm = new SizeRangeDetails();
            return View(vm);
        }
        public ActionResult SizeRangeDetailsGrid()
        {
            SizeRangeDetailsModel vm = new SizeRangeDetailsModel();
            SizeRangeDetailsManager sizeRangeDetailsManager = new SizeRangeDetailsManager();
            vm.SizeRangeDetailslsit = sizeRangeDetailsManager.Get();

            return PartialView("Partial/SizeRangeDetailsGrid", vm);
        }
        [HttpPost]
        public ActionResult SizeRangeDetailsView(int SizeRangeDetailsId)
        {
            SizeRangeDetailsManager sizeRangeDetailsManager = new SizeRangeDetailsManager();
            SizeRangeDetails sizeRangeDetails = new SizeRangeDetails();
            SizeRangeDetailsModel model = new SizeRangeDetailsModel();
            sizeRangeDetails = sizeRangeDetailsManager.GetSizeRangeDetailsId(SizeRangeDetailsId);
            if (sizeRangeDetails != null)
            {
                model.SizeRangeDetailsId = sizeRangeDetails.SizeRangeDetailsId;            
                model.SizeNo = sizeRangeDetails.SizeNo;
                model.SizenRangeName = sizeRangeDetails.SizeRangeName;
                model.CreatedDate = sizeRangeDetails.CreatedDate;
                model.UpdatedDate = sizeRangeDetails.UpdatedDate;
                model.CreatedBy = sizeRangeDetails.CreatedBy;
                model.UpdatedBy = sizeRangeDetails.UpdatedBy;
            }
            return PartialView("Partial/SizeRangeDetailsView", model);
        }
        #endregion

        #region Curd Operation
        [HttpPost]
        public ActionResult SizeRangedetail(SizeRangeDetailsModel model)
        {
            SizeRangeDetails sizeRangeDetail = new SizeRangeDetails();
            SizeRangeDetails sizeRangeDetails = new SizeRangeDetails();
            SizeRangeDetailsManager sizeRangeDetailsManager = new SizeRangeDetailsManager();
            sizeRangeDetails.SizeRangeDetailsId = model.SizeRangeDetailsId;          
            sizeRangeDetails.SizeNo = model.SizeNo;
            sizeRangeDetails.SizeRangeName = model.SizenRangeName;
            sizeRangeDetailsManager.Post(sizeRangeDetails);            
            return Json(sizeRangeDetails, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Update(SizeRangeDetailsModel model)
        {
            SizeRangeDetails sizeRangeDetail = new SizeRangeDetails();
            SizeRangeDetails sizeRangeDetails = new SizeRangeDetails();
            if (ModelState.IsValid)
            {
                SizeRangeDetailsManager sizeRangeDetailsManager = new SizeRangeDetailsManager();
                sizeRangeDetail = sizeRangeDetailsManager.GetSizeRangeDetailsId(model.SizeRangeDetailsId);
                if (sizeRangeDetail != null)
                {
                    sizeRangeDetails.SizeRangeDetailsId = model.SizeRangeDetailsId;                 
                    sizeRangeDetails.SizeNo = model.SizeNo;
                    sizeRangeDetails.SizeRangeName = model.SizenRangeName;
                    sizeRangeDetails.CreatedDate = sizeRangeDetail.CreatedDate;
                    sizeRangeDetails.UpdatedDate = DateTime.Now;
                    sizeRangeDetails.CreatedBy = sizeRangeDetail.CreatedBy;
                    sizeRangeDetails.UpdatedBy = sizeRangeDetail.UpdatedBy;
                    sizeRangeDetailsManager.Put(sizeRangeDetails);
                }
                else
                {
                    return Json(sizeRangeDetails, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(sizeRangeDetails, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(int SizeRangeDetailsId)
        {
            SizeRangeDetails sizeRangeDetails = new SizeRangeDetails();
            string status = "";
            SizeRangeDetailsManager sizeRangeDetailsManager = new SizeRangeDetailsManager();
            sizeRangeDetails = sizeRangeDetailsManager.GetSizeRangeDetailsId(SizeRangeDetailsId);
            if (sizeRangeDetails != null)
            {
                status = "Success";
                sizeRangeDetailsManager.Delete(sizeRangeDetails.SizeRangeDetailsId);
            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Helper Method
        public ActionResult Search(string filter)
        {
            List<SizeRangeDetails> SizeRangeDetailslist = new List<SizeRangeDetails>();
            SizeRangeDetailsManager sizeRangeDetailsManager = new SizeRangeDetailsManager();
            SizeRangeDetailslist = sizeRangeDetailsManager.Get();
            SizeRangeDetailslist = SizeRangeDetailslist.Where(x => x.SizeRangeName.ToLower().Trim().Contains(filter.ToLower().Trim())).ToList();
            SizeRangeDetailsModel model = new SizeRangeDetailsModel();
            model.SizeRangeDetailslsit = SizeRangeDetailslist;
            return PartialView("Partial/SizeRangeDetailsGrid", model);
        }
        #endregion


    }
}

MMS.Web/Views/SizeRangedetail/Partial/SizeRangeDetailsGrid.cshtml
@model MMS.Web.Models.SizeRangeDetailsModel.SizeRangeDetailsModel
@using MMS.Core.Entities;
@{
    MMS.Repository.Managers.SizeRangeMasterManager Manager = new MMS.Repository.Managers.SizeRangeMasterManager();
    SizeRangeMaster sizeRangeDetails = new SizeRangeMaster();
}
<div class="veh-tablewrap">
    <div class="veh-tablecont">
        <div id="sortMsg" style="text-align: center; color: Red;"></div>
        <div class="table-responsive table-td-padding padding-lr-6px table-row-bg" style="overflow: auto;">
            <table class="veh-table" id="empTable">
                <thead>
                    <tr class="color-code-top-btn">
                        <td colspan="11">
                            <input type="text" id="SeaarchID" placeholder="Search.." /><input type="button" value="Add" onclick="Add()">
                            <input type="button" value="Search" onclick=" Search()">
                        </td>
                    </tr>
                    <tr>
                        <th class="veh-1">
                            Si. No
                        </th>

                        <th class="veh-2">
                            SizeNo
                        </th>
                        <th class="veh-2">
                            Size Range Name
                        </th>
                        <th class="veh-3">
                            Edit/Delete
                        </th>

                    </tr>
                </thead>
                @if (Model.SizeRangeDetailslsit != null && Model.SizeRangeDetailslsit.Count > 0)
                {
                    int count = 1;
                <tbody>

                    @foreach (var SizeRange in Model.SizeRangeDetailslsit)
                        {
                        <tr>
                            <td class="veh-1" onclick="">@count</td>
                            <td class="veh-1" onclick="">@SizeRange.SizeNo</td>
                            <td class="veh-3">@SizeRange.SizeRangeName</td>
                            <td class="veh-1 edit-del-wrap">
                                <a href="javascript:void(0)" onclick="Edit('@SizeRange.SizeRangeDetailsId')" class="watchlist-edit" title="Edit"></a>
                                <a href="javascript:void(0)" id="DeleteVehicleWatchList" onclick="Delete('@SizeRange.SizeRangeDetailsId')" class="watchlist-delete" title="Delete"></a>

                            </td>
                        </tr>
                            count++;
                        }


                </tbody>
                }
                <tfoot class="footer-pager">
                    <tr>
                        <td colspan="4">
                            <div id="pager">
                                <form>
                                    <img src="@Url.Content("~/Content/images/first.png")" class="first" />
                                    <img src="@Url.Content("~/Content/images/prev.png")" class="prev" />
                                    <input type="text" class="pagedisplay" />
                                    <img src="@Url.Content("~/Content/images/next.png")" class="next" />
                                    <img src="@Url.Content("~/Content/images/last.png")" class="last" />
                                    <select class="pagesize">
                                        <option selected="selected" value="5">5</option>
                                        <option value="10">10</option>
                                        <option value="20">20</option>
                                        <option value="30">30</option>
                                        <option value="40">40</option>
                                    </select>
                                </form>
                            </div>

                        </td>

                    </tr>

                </tfoot>

          

            </table>
            @if (Model.SizeRangeDetailslsit != null && Model.SizeRangeDetailslsit.Count == 0)
            {
            <div style="color: red; font-size: 16px; text-align: center; width: 100%;">No Records Found</div>
            }
        </div>
    </div>

    <div id="EditColorPartial">
        @Html.Partial("Partial/SizeRangeDetailsView", Model)
    </div>


</div>


<script>
    $(document).ajaxStart(function () {
        $(".loader-overlay").css("display", "block");
    });

    $(document).ajaxComplete(function () {
        $(".loader-overlay").css("display", "none");
    });
    $(window).load(function () {
        $('.loader-overlay').fadeOut('fast');
    });
    function Search() {
        $.ajax({
            type: "POST",
            url: ' @Url.Action("Search", "SizeRangedetail")',
            data: { filter: $('#SeaarchID').val() },
            success: function (data) {
             
                $(".veh-tablewrap").html(data);
                $(".veh-tablewrap").show();
                $('#DivShow').hide();
                $('#EditColorPartial').hide();
            }
        });
    }

    function Cancel() {
        
        location.reload();
    }
    function Add() {
        $('.veh-tablecont').hide();
        $.ajax({
            type: "POST",
            url: ' @Url.Action("SizeRangeDetailsView", "SizeRangedetail")',
            data: { SizeRangeDetailsId: 0 },
            success: function (data) {
                $("#EditColorPartial").html(data);
                $("#EditColorPartial").show();
            }
        });

    }
    function Edit(arg) {
        $('.veh-tablecont').hide();
        $.ajax({
            type: "POST",
            url: ' @Url.Action("SizeRangeDetailsView", "SizeRangedetail")',
            data: { SizeRangeDetailsId: arg },
            success: function (data) {
                $("#EditColorPartial").html(data);
                $("#EditColorPartial").show();
            }
        });

    }
    function Delete(arg) {
        var answer = confirm("Are you sure want to delete?");
        if (answer) {
            $.ajax({
                type: 'POST',
                url: ' @Url.Action("Delete", "SizeRangedetail")',
                data: { SizeRangeDetailsId: arg },
                success: function (data) {
                    if (data == "Success") {
                        alert('Deleted Successfully.');
                        location.href = "/SizeRangedetail/SizeRangedetail";
                        return false;
                    }
                    else {
                        alert('Color Details deletion failed.');
                    }

                },
                error: function (ex) {
                    alert('This Color Already Exist in the database.');
                }
            });
        }
        else {
            return false;
        }
    }


</script>

MMS.Web/Views/SizeRangedetail/Partial/SizeRangeDetailsView.cshtml
@model MMS.Web.Models.SizeRangeDetailsModel.SizeRangeDetailsModel
@{
    int id = Model.SizeRangeDetailsId;
    Session["SizeRangeDetailsId"] = id;
}

<div class="right-form-section clearfix">
    <form role="form" class="form-inline">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12 no-padding">
                    <div class="field-section">
                        <div class="form-group">
                            <div class="col-md-5 col-sm-5 col-lg-5 col-xs-12 stage_lable_sec">
                                <label class="form-label" for="text">SizeNo</label>
                            </div>
                            <div class="col-md-7 col-sm-7 col-lg-7 col-xs-12">
                                @Html.TextBoxFor(m => m.SizeNo, new { @class = "form-control text-field" })
                            </div>
                        </div>
                    </div>
                    <div class="field-section">
                        <div class="form-group">
                            <div class="col-md-5 col-sm-5 col-lg-5 col-xs-12 stage_lable_sec">
                                <label class="form-label" for="text">Size Master name</label>
                            </div>
                            @Html.HiddenFor(m => m.SizeRangeDetailsId)
                            <div class="col-md-7 col-sm-7 col-lg-7 col-xs-12">
                                @Html.TextBoxFor(m => m.SizenRangeName, new { @class = "form-control text-field" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-footer">
            <div class="row">
                <div style="margin: 15px 0px;" class="col-md-12 col-sm-12 col-lg-12 col-xs-12 text-center">
                    <input type="button" onclick="Cancel()" class="btn btn-default btn-style width-78" title="Back" value="Back">
                    @if (Model != null && Model.SizeRangeDetailsId != 0)
                    {

                        <input type="button" onclick="Update()" class="btn btn-default btn-style width-78" id="SizeRangeMasterId" title="Update" value="Update">
                    }
                    else
                    {
                        <input type="button" onclick="Save()" class="btn btn-default btn-style width-78" title="Save" value="Save">
                    }
                    <button class="btn btn-default btn-style width-78" type="submit">Clear</button>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    $(document).ajaxStart(function () {
        $(".loader-overlay").css("display", "block");
    });

    $(document).ajaxComplete(function () {
        $(".loader-overlay").css("display", "none");
    });
    $(window).load(function () {
        $('.loader-overlay').fadeOut('fast');
    });
</script>